### PR TITLE
fix: test failure cases on windows

### LINKED ISSUE #1010: Support Windows with the CI system
It was shown in [this test run](https://github.com/open-telemetry/opentelemetry-go-contrib/runs/3353556306) that this project currently does not successfully complete tests on (some (?)) Windows systems.

```
go test ./... + race in ./exporters/metric/cortex/utils
go: downloading gopkg.in/yaml.v3 v3.0.0-20210107192922-496545a6307b
=== RUN   TestNewConfig
=== RUN   TestNewConfig/Valid_Config_file
    config_utils_test.go:135: 
        	Error Trace:	config_utils_test.go:135
        	Error:      	Not equal: 
        	            	expected: viper.ConfigFileNotFoundError(viper.ConfigFileNotFoundError{name:"config.yml", locations:"[D:\\a\\opentelemetry-go-contrib\\opentelemetry-go-contrib\\exporters\\metric\\cortex\\utils D:\\test]"})
        	            	actual  : <nil>(<nil>)
        	Test:       	TestNewConfig/Valid_Config_file
=== RUN   TestNewConfig/No_Timeout
    config_utils_test.go:135: 
        	Error Trace:	config_utils_test.go:135
        	Error:      	Not equal: 
        	            	expected: viper.ConfigFileNotFoundError(viper.ConfigFileNotFoundError{name:"config.yml", locations:"[D:\\a\\opentelemetry-go-contrib\\opentelemetry-go-contrib\\exporters\\metric\\cortex\\utils D:\\test]"})
        	            	actual  : <nil>(<nil>)
        	Test:       	TestNewConfig/No_Timeout
=== RUN   TestNewConfig/No_Endpoint_URL
    config_utils_test.go:135: 
        	Error Trace:	config_utils_test.go:135
        	Error:      	Not equal: 
        	            	expected: viper.ConfigFileNotFoundError(viper.ConfigFileNotFoundError{name:"config.yml", locations:"[D:\\a\\opentelemetry-go-contrib\\opentelemetry-go-contrib\\exporters\\metric\\cortex\\utils D:\\test]"})
        	            	actual  : <nil>(<nil>)
        	Test:       	TestNewConfig/No_Endpoint_URL
=== RUN   TestNewConfig/Two_passwords
    config_utils_test.go:135: 
        	Error Trace:	config_utils_test.go:135
        	Error:      	Not equal: 
        	            	expected: viper.ConfigFileNotFoundError(viper.ConfigFileNotFoundError{name:"config.yml", locations:"[D:\\a\\opentelemetry-go-contrib\\opentelemetry-go-contrib\\exporters\\metric\\cortex\\utils D:\\test]"})
        	            	actual  : *errors.errorString(&errors.errorString{s:"cannot have two passwords in the YAML file"})
        	Test:       	TestNewConfig/Two_passwords
=== RUN   TestNewConfig/Two_Bearer_Tokens
    config_utils_test.go:135: 
        	Error Trace:	config_utils_test.go:135
        	Error:      	Not equal: 
        	            	expected: viper.ConfigFileNotFoundError(viper.ConfigFileNotFoundError{name:"config.yml", locations:"[D:\\a\\opentelemetry-go-contrib\\opentelemetry-go-contrib\\exporters\\metric\\cortex\\utils D:\\test]"})
        	            	actual  : *errors.errorString(&errors.errorString{s:"cannot have two bearer tokens in the YAML file"})
        	Test:       	TestNewConfig/Two_Bearer_Tokens
=== RUN   TestNewConfig/Custom_Quantiles
    config_utils_test.go:135: 
        	Error Trace:	config_utils_test.go:135
        	Error:      	Not equal: 
        	            	expected: viper.ConfigFileNotFoundError(viper.ConfigFileNotFoundError{name:"config.yml", locations:"[D:\\a\\opentelemetry-go-contrib\\opentelemetry-go-contrib\\exporters\\metric\\cortex\\utils D:\\test]"})
        	            	actual  : <nil>(<nil>)
        	Test:       	TestNewConfig/Custom_Quantiles
=== RUN   TestNewConfig/Custom_Histogram_Boundaries
    config_utils_test.go:135: 
        	Error Trace:	config_utils_test.go:135
        	Error:      	Not equal: 
        	            	expected: viper.ConfigFileNotFoundError(viper.ConfigFileNotFoundError{name:"config.yml", locations:"[D:\\a\\opentelemetry-go-contrib\\opentelemetry-go-contrib\\exporters\\metric\\cortex\\utils D:\\test]"})
        	            	actual  : <nil>(<nil>)
        	Test:       	TestNewConfig/Custom_Histogram_Boundaries
--- FAIL: TestNewConfig (0.03s)
    --- FAIL: TestNewConfig/Valid_Config_file (0.03s)
    --- FAIL: TestNewConfig/No_Timeout (0.00s)
    --- FAIL: TestNewConfig/No_Endpoint_URL (0.00s)
    --- FAIL: TestNewConfig/Two_passwords (0.00s)
    --- FAIL: TestNewConfig/Two_Bearer_Tokens (0.00s)
    --- FAIL: TestNewConfig/Custom_Quantiles (0.00s)
    --- FAIL: TestNewConfig/Custom_Histogram_Boundaries (0.00s)
=== RUN   TestWithFilepath
=== RUN   TestWithFilepath/Filepath_provided,_successful_construction_of_Config
    config_utils_test.go:184: 
        	Error Trace:	config_utils_test.go:184
        	Error:      	Received unexpected error:
        	            	Config File "config.yml" Not Found in "[D:\\a\\opentelemetry-go-contrib\\opentelemetry-go-contrib\\exporters\\metric\\cortex\\utils D:\\test D:\\success]"
        	Test:       	TestWithFilepath/Filepath_provided,_successful_construction_of_Config
=== RUN   TestWithFilepath/Filepath_not_provided,_unsuccessful_construction_of_Config
--- FAIL: TestWithFilepath (0.00s)
    --- FAIL: TestWithFilepath/Filepath_provided,_successful_construction_of_Config (0.00s)
    --- PASS: TestWithFilepath/Filepath_not_provided,_unsuccessful_construction_of_Config (0.00s)
=== RUN   TestWithClient
--- FAIL: TestWithClient (0.00s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0xa0 pc=0x1b10a6d]

goroutine 18 [running]:
testing.tRunner.func1.1(0x1bb5cc0, 0x21b2590)
	C:/hostedtoolcache/windows/go/1.15.15/x64/src/testing/testing.go:1072 +0x310
testing.tRunner.func1(0xc0003ae900)
	C:/hostedtoolcache/windows/go/1.15.15/x64/src/testing/testing.go:1075 +0x43a
panic(0x1bb5cc0, 0x21b2590)
	C:/hostedtoolcache/windows/go/1.15.15/x64/src/runtime/panic.go:969 +0x1c7
go.opentelemetry.io/contrib/exporters/metric/cortex/utils_test.TestWithClient(0xc0003ae900)
	D:/a/opentelemetry-go-contrib/opentelemetry-go-contrib/exporters/metric/cortex/utils/config_utils_test.go:212 +0x1ed
testing.tRunner(0xc0003ae900, 0x1cba1f0)
	C:/hostedtoolcache/windows/go/1.15.15/x64/src/testing/testing.go:1123 +0xef
created by testing.(*T).Run
	C:/hostedtoolcache/windows/go/1.15.15/x64/src/testing/testing.go:1168 +0x2b3
FAIL	go.opentelemetry.io/contrib/exporters/metric/cortex/utils	0.061s
FAIL
mingw32-make: *** [Makefile:123: test-short] Error 1
```

This failure needs to be resolved and the `TODO` left in #1009 needs to be resolved:

https://github.com/open-telemetry/opentelemetry-go-contrib/blob/07164a8b4d6bf146a3b3ab3c05512ff430241777/.github/workflows/ci.yml#L111-L112

### PR DESCRIPTION
**Pull request by laojianzi**
Fixed #1010 

---

~~But it's not clear what the problem is here~~

https://github.com/laojianzi/opentelemetry-go-contrib/runs/3504741867?check_suite_focus=true#step:6:297
> === RUN   ExampleExporter
--- FAIL: ExampleExporter (0.00s)
got:
myrecorder.max:100|g|#env:dev,l:1,service.name:unknown_service:datadog.test.exe,telemetry.sdk.language:go,telemetry.sdk.name:opentelemetry,telemetry.sdk.version:1.0.0-RC1
want:
myrecorder.max:100|g|#env:dev,l:1,service.name:unknown_service:datadog.test,telemetry.sdk.language:go,telemetry.sdk.name:opentelemetry,telemetry.sdk.version:1.0.0-RC1
FAIL
FAIL	go.opentelemetry.io/contrib/exporters/metric/datadog	0.026s
FAIL
mingw32-make: *** [Makefile:130: test-short] Error 1
Error: Process completed with exit code 1.

Resolved in https://github.com/open-telemetry/opentelemetry-go-contrib/pull/1047#issuecomment-913096792

### CODE REVIEW

**Comment by Aneurysm9** [comment]
The DataDog test failure seems to be caused by the default service name being `unknown_service:datadog.test.exe` on windows and the `.exe` is unexpected.  It should be possible to solve that by giving the `TracerProvider` a resource with an explicitly set service name so that it doesn't vary by platform.

**Comment by laojianzi** [comment]
> The DataDog test failure seems to be caused by the default service name being `unknown_service:datadog.test.exe` on windows and the `.exe` is unexpected. It should be possible to solve that by giving the `TracerProvider` a resource with an explicitly set service name so that it doesn't vary by platform.

thx, I think I found the answer here 😃 

https://github.com/open-telemetry/opentelemetry-go/blob/v1.0.0-RC2/semconv/v1.4.0/resource.go#L785

**Review by pellared — APPROVED** [review]
nice 👍

**Comment by laojianzi** [comment]
@Aneurysm9 pls review again :upside_down_face:

File: exporters/metric/datadog/example_test.go [hunk 1]
```diff
@@ -67,7 +68,7 @@ func ExampleExporter() {
 		global.SetMeterProvider(pusher.MeterProvider())
 		meter := global.Meter("marwandist")
 		m := metric.Must(meter).NewInt64Histogram("myrecorder")
-		meter.RecordBatch(context.Background(), []attribute.KeyValue{attribute.Int("l", 1)},
+		meter.RecordBatch(context.Background(), []attribute.KeyValue{attribute.Int("l", 1), semconv.ServiceNameKey.String("ExampleExporter")},
```
Comment (Aneurysm9) [inline exporters/metric/datadog/example_test.go:71]: `service_name` is a resource attribute, so this should be handled by passing a `*Resource` to `controller.New()` via the [`WithResource()`](https://pkg.go.dev/go.opentelemetry.io/otel/sdk/metric@v0.23.0/controller/basic#WithResource) option.

Comment (laojianzi) [reply exporters/metric/datadog/example_test.go]: No problem

please review again 🙃

**Review by dashpole — APPROVED** [review]

**Comment by laojianzi** [comment]
``` shell
=== RUN   TestHostNetwork
    assertion_compare.go:342:
        	Error Trace:	host_test.go:235
        	Error:      	"10000" is not less than or equal to "7837"
        	Test:       	TestHostNetwork
        	Messages:   	[]
--- FAIL: TestHostNetwork
```

This mistake was accidental and increasing sleep can only improve the chances of success, any ideas to help?

**Comment by laojianzi** [comment]
> ```shell
> === RUN   TestHostNetwork
>     assertion_compare.go:342:
>         	Error Trace:	host_test.go:235
>         	Error:      	"10000" is not less than or equal to "7837"
>         	Test:       	TestHostNetwork
>         	Messages:   	[]
> --- FAIL: TestHostNetwork
> ```
> 
> This mistake was accidental and increasing sleep can only improve the chances of success, any ideas to help?
> 
> on windows

---

@Aneurysm9 I used the following method to debug and the test passed in 3s/8s/10s ... etc, so I can't use sleep to guarantee the success of the test, do you think it's reasonable to wait for sent/recv 

 Is it reasonable to wait until sent/recv is satisfied until the go test times out?

https://github.com/open-telemetry/opentelemetry-go-contrib/blob/8e44f3f02293665b0547280bf151da43d9a8fb2a/instrumentation/host/host_test.go#L222-L223

https://github.com/open-telemetry/opentelemetry-go-contrib/blob/330ca09f95f640e24829386b148c587cef1bbd95/instrumentation/host/host_test.go#L222-L232

**Comment by pellared** [comment]
> I used the following method to debug and the test passed in 3s/8s/10s ... etc, so I can't use sleep to guarantee the success of the test, do you think it's reasonable to wait for sent/recv

At first glance it looks like a good candidate to use [`require.Eventually`](https://pkg.go.dev/github.com/stretchr/testify/require#Eventually). WDYT?

**Comment by laojianzi** [comment]
> At first glance it looks like a good candidate to use [`require.Eventually`](https://pkg.go.dev/github.com/stretchr/testify/require#Eventually). WDYT?

Of course, but how long should we wait ? as this process seems very unstable on Windows :thinking:

**Comment by pellared** [comment]
> Of course, but how long should we wait ? as this process seems very unstable on Windows

I would try 30s - should be long enough I guess 😉

**Review by pellared — APPROVED** [review]

**Comment by laojianzi** [comment]
@pellared Thank you for your help 👍

File: instrumentation/host/host_test.go [hunk 2]
```diff
@@ -220,20 +221,18 @@ func TestHostNetwork(t *testing.T) {
...
-
-	impl.RunAsyncInstruments()
+	require.Eventually(t, func() bool {
+		hostAfter, err := net.IOCountersWithContext(ctx, false)
+		require.NoError(t, err)
 
-	hostAfter, err := net.IOCountersWithContext(ctx, false)
-	require.NoError(t, err)
+		return uint64(howMuch) <= hostAfter[0].BytesSent-hostBefore[0].BytesSent &&
+			uint64(howMuch) <= hostAfter[0].BytesRecv-hostBefore[0].BytesRecv
```
Comment (Aneurysm9) [inline instrumentation/host/host_test.go:229]: Can you keep these as assertions?  Doing so should help in understanding where a failure occurred if this test starts failing in the future.

File: exporters/metric/datadog/example_test.go [hunk 3]
```diff
@@ -57,12 +59,15 @@ func ExampleExporter() {
 	go func() {
 		defer exp.Close()
 		processor := basic.New(selector, exp)
-		pusher := controller.New(processor, controller.WithExporter(exp), controller.WithCollectPeriod(time.Second*10))
+		pusher := controller.New(processor, controller.WithExporter(exp), controller.WithCollectPeriod(time.Second*10),
+			controller.WithResource(resource.Default()),
+			controller.WithResource(resource.NewSchemaless(semconv.ServiceNameKey.String("ExampleExporter"))))
```
Comment (Aneurysm9) [inline exporters/metric/datadog/example_test.go:64]: Should this use `New()` instead of `NewSchemaless()`?  We have a schema from `semconv.SchemaURL`.

File: instrumentation/host/host_test.go (hunk 2 above)
Comment (laojianzi) [reply instrumentation/host/host_test.go:229]: Thanks @Aneurysm9

Because it is necessary to wait for "BytesSent" and "BytesRecv" all the time, they are not assert here.

There should only be one timeout error here and it will be tracked to the `require.Eventually` line, but 30 seconds will cause the go test to time out without printing the error tracking message, so consider updating it to <30 seconds?

https://github.com/open-telemetry/opentelemetry-go-contrib/pull/1047#issuecomment-929000722 The idea. WDYT?

File: exporters/metric/datadog/example_test.go (hunk 3 above)
Comment (laojianzi) [reply exporters/metric/datadog/example_test.go:64]: Thanks, @Aneurysm9

Okey! like this?

```go
ctx := context.Background()
serviceName, err := resource.New(ctx, resource.WithAttributes(semconv.ServiceNameKey.String("ExampleExporter")))
if err != nil {
	panic(err)
}

cont := controller.New(processor, controller.WithExporter(exp), controller.WithCollectPeriod(time.Second*10),
	controller.WithResource(resource.Default()), controller.WithResource(serviceName))
```

File: instrumentation/host/host_test.go (hunk 2 above)
Comment (laojianzi) [reply instrumentation/host/host_test.go:229]: This is the error trace info for the 20s timeout

> === RUN   TestHostNetwork
    host_test.go:222: 
        	Error Trace:	host_test.go:222
        	Error:      	Condition never satisfied
        	Test:       	TestHostNetwork
--- FAIL: TestHostNetwork (20.00s)

**Review by MadVikingGod — APPROVED** [review]
Can you please merge in main to resolve some conflicts?

Other than the outstanding comments it LGTM

**Comment by laojianzi** [comment]
> Can you please merge in main to resolve some conflicts?
> 
> Other than the outstanding comments it LGTM

@MadVikingGod Done
