### PR TITLE
Fix panic for nil attributes and move convert funcs to internal/shared/logutil

### LINKED ISSUE #6235: nil pointer field cause panic
### Description

After add otellogrus hook, when logging with a field which contains a nil pointer would cause internal panic

### Environment

- OS: any
- Architecture: any
- Go Version: 1.23.0
- `go.opentelemetry.io/contrib/bridges/otellogrus` version: 0.5.0

### Steps To Reproduce

```go
package main

import (
	"github.com/sirupsen/logrus"
	"go.opentelemetry.io/contrib/bridges/otellogrus"
)

type ATopicHandler struct {
	some string
}

func main() {
	var a *ATopicHandler
	logger := logrus.New()
	hook := otellogrus.NewHook("test")
	logger.AddHook(hook)
	logger.WithField("a", a).Error("error")
}
```

```shell
panic: reflect: call of reflect.Value.Interface on zero Value

goroutine 1 [running]:
reflect.valueInterface({0x0?, 0x0?, 0x0?}, 0x0?)
        /Users/m1heng/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.0.darwin-arm64/src/reflect/value.go:1486 +0xfc
reflect.Value.Interface(...)
        /Users/m1heng/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.0.darwin-arm64/src/reflect/value.go:1481
go.opentelemetry.io/contrib/bridges/otellogrus.convertValue({0x10446e300, 0x0})
        /Users/m1heng/go/pkg/mod/go.opentelemetry.io/contrib/bridges/otellogrus@v0.5.0/hook.go:233 +0x3e4
go.opentelemetry.io/contrib/bridges/otellogrus.convertFields(0x1400011ca80)
        /Users/m1heng/go/pkg/mod/go.opentelemetry.io/contrib/bridges/otellogrus@v0.5.0/hook.go:180 +0xec
go.opentelemetry.io/contrib/bridges/otellogrus.(*Hook).convertEntry(_, _)
        /Users/m1heng/go/pkg/mod/go.opentelemetry.io/contrib/bridges/otellogrus@v0.5.0/hook.go:170 +0x9c
go.opentelemetry.io/contrib/bridges/otellogrus.(*Hook).Fire(0x1400011c9c0, 0x1400010ad08?)
        /Users/m1heng/go/pkg/mod/go.opentelemetry.io/contrib/bridges/otellogrus@v0.5.0/hook.go:159 +0x38
github.com/sirupsen/logrus.LevelHooks.Fire(0x1400010ad48?, 0x10ad08?, 0x1400015c0e0)
        /Users/m1heng/go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/hooks.go:28 +0x78
github.com/sirupsen/logrus.(*Entry).fireHooks(0x1400015c0e0)
        /Users/m1heng/go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:280 +0x20c
github.com/sirupsen/logrus.(*Entry).log(0x1400015c070, 0x2, {0x140001020fa, 0x5})
        /Users/m1heng/go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:242 +0x3b0
github.com/sirupsen/logrus.(*Entry).Log(0x1400015c070, 0x2, {0x1400010af28?, 0x10446e300?, 0x0?})
        /Users/m1heng/go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:304 +0x60
github.com/sirupsen/logrus.(*Entry).Error(...)
        /Users/m1heng/go/pkg/mod/github.com/sirupsen/logrus@v1.9.3/entry.go:333
main.main()
        /Users/m1heng/xxxxx/main.go:19 +0x134
exit status 2
```

### Expected behavior
log normally

### PR DESCRIPTION
**Pull request by m1heng**
This pull request aligns the `convertValue` function in the `otellogrus` package with the `otellogr`. 
Also fix #6235

### CODE REVIEW

**Comment by pellared** [comment]
It would be better to put `convertValue` under `internal/shared` and use `//go:generate gotmpl` to reuse the code in log bridges (`otellogrus, `otelzap`, `otellogr`).

**Comment by m1heng** [comment]
@pellared just did it, also added some nil pointer test

File: internal/shared/logutil/convert.go.tmpl [hunk 1]
```diff
@@ -1,7 +1,10 @@
+// Code created by gotmpl. DO NOT MODIFY.
+// source: internal/shared/logutil/convert.go.tmpl
+
 // Copyright The OpenTelemetry Authors
 // SPDX-License-Identifier: Apache-2.0
 
-package otellogr // import "go.opentelemetry.io/contrib/bridges/otellogr"
+package logutil // import "go.opentelemetry.io/contrib/internal/shared/logutil"
```
Comment (pellared) [inline internal/shared/logutil/convert.go.tmpl:7]: Can you make the the package name as an template parameter/input and put it directly to the pacakge (instead of inside `internal/logutil`?

File: internal/shared/logutil/convert.go.tmpl [hunk 2]
```diff
@@ -17,7 +20,7 @@ import (
 // convertKVs converts a list of key-value pairs to a list of [log.KeyValue].
 // The last [context.Context] value is returned as the context.
 // If no context is found, the original context is returned.
-func convertKVs(ctx context.Context, keysAndValues ...any) (context.Context, []log.KeyValue) {
+func ConvertKVs(ctx context.Context, keysAndValues ...any) (context.Context, []log.KeyValue) {
```
Comment (pellared) [inline internal/shared/logutil/convert.go.tmpl:23]: Can we unexport this function (and move it to the bridge packages)?

File: internal/shared/logutil/convert.go.tmpl [hunk 3]
```diff
@@ -146,9 +149,9 @@ func convertValue(v any) log.Value {
 	return log.StringValue(fmt.Sprintf("unhandled: (%s) %+v", t, v))
 }
 
-// convertUintValue converts a uint64 to a log.Value.
+// ConvertUintValue converts a uint64 to a log.Value.
 // If the value is too large to fit in an int64, it is converted to a string.
-func convertUintValue(v uint64) log.Value {
+func ConvertUintValue(v uint64) log.Value {
```
Comment (pellared) [inline internal/shared/logutil/convert.go.tmpl:154]: Can we unexport this?

**Review by pellared — COMMENTED** [review]
> Also this would leads to a semi-breaking change.

I think these changes are good 👍

**Comment by pellared** [comment]
Can you also please update the changelog and add an entry for each package where https://github.com/open-telemetry/opentelemetry-go-contrib/issues/6235 is fixed.

**Comment by m1heng** [comment]
done

**Comment by m1heng** [comment]
you want `func ConvertValue` to be private in all package?

**Comment by pellared** [comment]
> you want `func ConvertValue` to be private in all package?

Correct.

**Comment by m1heng** [comment]
just changed to private

**Review by pellared — APPROVED** [review]

**Review by MrAlias — APPROVED** [review]

**Review by dmathieu — APPROVED** [review]

**Comment by pellared** [comment]
@m1heng, thank you very much for your contribution 🏅
